import { CheckCircle2, CornerDownLeft, FilePenLine, LoaderCircle, MessageSquareText, Sparkles, WandSparkles } from 'lucide-react'
import Header from '../components/Header'

export default function AIAssistant({ text, setText, preview, loading, onPreview, onApply }) {
  const data = preview?.data || {}
  const confidence = preview ? Math.round((preview.confidence > 1 ? preview.confidence / 100 : preview.confidence || .92) * 100) : 0
  return <><Header title="AI 도우미" subtitle="자연스럽게 말하면 업무와 일정으로 정리해 드립니다."/><div className="content ai-layout">
    <section className="assistant-panel"><div className="assistant-heading"><span><Sparkles/></span><div><h2>무엇을 도와드릴까요?</h2><p>해야 할 일, 완료한 일, 일정 변경을 자유롭게 적어보세요.</p></div></div><div className="suggestions"><button onClick={()=>setText('이번 주 금요일까지 제안서 초안을 작성해야 해. 중요도는 높음으로 해줘.')}><FilePenLine/>새 업무 등록</button><button onClick={()=>setText('오늘 고객사 미팅을 완료했고, 다음 주 화요일에 후속 연락 일정 추가해줘.')}><MessageSquareText/>완료 업무 기록</button><button onClick={()=>setText('진행 중인 일을 보고 오늘 가장 먼저 할 일 3개를 추천해줘.')}><WandSparkles/>오늘 업무 추천</button></div><div className="prompt-box"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="예: 다음 주 화요일 오후 2시에 고객사 미팅을 추가하고, 하루 전에 준비 자료 검토 업무도 만들어줘."/><footer><span>AI가 적용 전 내용을 미리 보여드려요.</span><button className="primary" disabled={!text.trim()||loading} onClick={onPreview}>{loading?<LoaderCircle className="spin"/>:<CornerDownLeft/>} 분석하기</button></footer></div></section>
    <section className={`ai-result ${preview?'visible':''}`}><div className="section-title"><div><h2>AI 분석 결과</h2><p>적용 전에 내용을 확인하세요.</p></div>{preview?<span className="confidence">{confidence}% 확신</span>:null}</div>{preview?<><div className="preview-item"><span className="preview-icon"><CheckCircle2/></span><div><small>{preview.action==='update'?'항목 수정':'새 항목'} · {preview.entity}</small><h3>{data.title||data.content||'새 항목'}</h3><dl><div><dt>시작</dt><dd>{data.start_date||data.start_at||data.todo_date||data.log_date||'-'}</dd></div><div><dt>완료</dt><dd>{data.due_date||data.end_at||'-'}</dd></div><div><dt>우선순위</dt><dd>{data.priority||'보통'}</dd></div></dl><p>{data.description||text}</p></div></div><div className="result-actions"><button className="secondary" onClick={()=>setText(text)}>내용 수정</button><button className="primary" onClick={onApply}>이대로 적용</button></div></>:<div className="ai-empty"><Sparkles/><strong>분석 결과가 여기에 표시됩니다</strong><p>왼쪽 입력창에 내용을 적고 분석하기를 눌러보세요.</p></div>}</section>
  </div></>
}
