import { useMemo, useState } from 'react'
import { ChevronLeft,ChevronRight,MapPin,Plus } from 'lucide-react'
import Header from '../components/Header'
import Modal from '../components/Modal'

const weekdays=['일','월','화','수','목','금','토']
const pad=n=>String(n).padStart(2,'0')
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`
const localInput=value=>{if(!value)return '';const d=new Date(value);return `${dateKey(d)}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
const labelDate=d=>`${d.getFullYear()}년 ${d.getMonth()+1}월 ${d.getDate()}일`

function EventForm({event,initialDate,onSave,onDelete,onCancel}){
  const start=event?.start_at||event?.start||`${initialDate}T09:00:00`,end=event?.end_at||event?.end||`${initialDate}T10:00:00`
  const submit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(new Date(d.end_at)<=new Date(d.start_at)){alert('종료 시간은 시작 시간보다 늦어야 합니다.');return}onSave({...d,title:d.title.trim(),description:d.description.trim(),location:d.location.trim(),start_at:`${d.start_at}:00`,end_at:`${d.end_at}:00`})}
  return <form className="form-grid" onSubmit={submit}><label className="span-2">일정 제목<input name="title" defaultValue={event?.title||''} required autoFocus placeholder="일정 제목"/></label><label>시작<input name="start_at" type="datetime-local" required defaultValue={localInput(start)}/></label><label>종료<input name="end_at" type="datetime-local" required defaultValue={localInput(end)}/></label><label className="span-2">장소<input name="location" defaultValue={event?.location||''} placeholder="장소 또는 화상회의 링크"/></label><label className="span-2">메모<textarea name="description" rows="4" defaultValue={event?.description||''} placeholder="참석자, 준비물 등"/></label><div className="form-actions span-2">{event&&onDelete?<button type="button" className="danger-button" onClick={onDelete}>삭제</button>:null}<span className="form-spacer"/><button type="button" className="secondary" onClick={onCancel}>취소</button><button className="primary">{event?'변경사항 저장':'일정 등록'}</button></div></form>
}

export default function Calendar({events,onCreate,onUpdate,onDelete}){
 const [cursor,setCursor]=useState(()=>new Date()),[view,setView]=useState('month'),[editing,setEditing]=useState(null),[newDate,setNewDate]=useState(null)
 const dayStart=useMemo(()=>{const d=new Date(cursor);d.setHours(0,0,0,0);return d},[cursor])
 const move=amount=>setCursor(d=>{const n=new Date(d);if(view==='month')n.setMonth(n.getMonth()+amount);else n.setDate(n.getDate()+amount*(view==='week'?7:1));return n})
 const startOfWeek=useMemo(()=>{const d=new Date(dayStart);d.setDate(d.getDate()-d.getDay());return d},[dayStart])
 const weekDays=Array.from({length:7},(_,i)=>{const d=new Date(startOfWeek);d.setDate(d.getDate()+i);return d})
 const monthCells=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),grid=new Date(first);grid.setDate(1-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(grid);d.setDate(grid.getDate()+i);return {date:d,current:d.getMonth()===m}})},[cursor])
 const inDay=(event,d)=>dateKey(new Date(event.start_at||event.start))===dateKey(d)
 const openNew=d=>setNewDate(dateKey(d))
 const title=view==='month'?`${cursor.getFullYear()}년 ${cursor.getMonth()+1}월`:view==='week'?`${labelDate(weekDays[0])} – ${labelDate(weekDays[6])}`:labelDate(cursor)
 const eventButton=e=><button key={e.id} className="cal-event" onClick={ev=>{ev.stopPropagation();setEditing(e)}}><b>{e.title}</b><small>{new Date(e.start_at||e.start).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</small></button>
 return <><Header title="일정" subtitle="월·주·일 보기로 업무 일정을 관리하세요." action="새 일정" onAction={()=>openNew(cursor)}/><div className="content"><div className="calendar-tools"><div className="month-switch"><button className="secondary today-button" onClick={()=>setCursor(new Date())}>오늘</button><button className="icon-button" aria-label="이전" onClick={()=>move(-1)}><ChevronLeft/></button><h2>{title}</h2><button className="icon-button" aria-label="다음" onClick={()=>move(1)}><ChevronRight/></button></div><div className="view-switch">{[['month','월'],['week','주'],['day','일']].map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{label}</button>)}</div></div>
 {view==='month'?<section className="calendar"><div className="weekdays">{weekdays.map(d=><div key={d}>{d}</div>)}</div><div className="calendar-grid">{monthCells.map(c=><div className={`${c.current?'':'outside'} ${dateKey(c.date)===dateKey(new Date())?'today-cell':''}`} key={dateKey(c.date)} onClick={()=>openNew(c.date)}><span>{c.date.getDate()}</span>{events.filter(e=>inDay(e,c.date)).slice(0,4).map(eventButton)}{events.filter(e=>inDay(e,c.date)).length>4?<small className="more-events">+{events.filter(e=>inDay(e,c.date)).length-4}개 더보기</small>:null}<button className="cell-add" aria-label={`${dateKey(c.date)} 일정 추가`}><Plus/></button></div>)}</div></section>:view==='week'?<section className="calendar week-calendar"><div className="weekdays">{weekDays.map(d=><div className={dateKey(d)===dateKey(new Date())?'today-column':''} key={dateKey(d)}>{weekdays[d.getDay()]} <b>{d.getDate()}</b></div>)}</div><div className="week-grid">{weekDays.map(d=><div key={dateKey(d)} onClick={()=>openNew(d)}>{events.filter(e=>inDay(e,d)).map(eventButton)}{!events.some(e=>inDay(e,d))?<span className="day-empty">일정을 추가하려면 누르세요</span>:null}</div>)}</div></section>:<section className="calendar day-calendar" onClick={()=>openNew(cursor)}><header><b>{weekdays[cursor.getDay()]}요일</b><span>{dateKey(cursor)}</span></header>{events.filter(e=>inDay(e,cursor)).length?events.filter(e=>inDay(e,cursor)).sort((a,b)=>new Date(a.start_at||a.start)-new Date(b.start_at||b.start)).map(e=><button className="day-event" key={e.id} onClick={ev=>{ev.stopPropagation();setEditing(e)}}><time>{new Date(e.start_at||e.start).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</time><div><b>{e.title}</b>{e.location?<small><MapPin/> {e.location}</small>:null}<p>{e.description}</p></div></button>):<p className="empty-state">등록된 일정이 없습니다. 눌러서 일정을 추가하세요.</p>}</section>}
 </div>{(editing||newDate)?<Modal title={editing?'일정 수정':'새 일정'} onClose={()=>{setEditing(null);setNewDate(null)}}><EventForm event={editing} initialDate={newDate||dateKey(cursor)} onCancel={()=>{setEditing(null);setNewDate(null)}} onSave={data=>{editing?onUpdate(editing,data):onCreate(data);setEditing(null);setNewDate(null)}} onDelete={editing?()=>{if(confirm(`‘${editing.title}’ 일정을 삭제할까요?`)){onDelete(editing);setEditing(null)}}:null}/></Modal>:null}</>
}
