import { CalendarClock, Check, ChevronRight, Circle, Clock3, Plus, Sparkles } from 'lucide-react'
import Header from '../components/Header'

const dateText = new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'long' }).format(new Date())

export default function Today({ tasks, events, notes, onAddNote, onToggleTask, goAI }) {
  const active = tasks.filter(t => t.status !== 'done').slice(0, 4)
  return <><Header title="오늘의 일" subtitle={`${dateText} · 오늘도 차근차근 해볼까요?`}/><div className="content today-grid"><section className="focus-panel"><div className="section-title"><div><h2>오늘 할 일</h2><p>{active.length}개의 업무가 기다리고 있어요</p></div><button className="text-button">전체 보기 <ChevronRight size={16}/></button></div><div className="task-list">{active.map(task => <button className="task-row" key={task.id} onClick={() => onToggleTask(task)}><span className="check-circle"><Circle/><Check/></span><span className="task-main"><strong>{task.title}</strong><small><span className={`priority ${task.priority}`}></span>{task.category || '업무'} · {task.due_date}까지</small></span><span className="mini-progress"><i style={{width:`${task.progress}%`}}></i></span><b>{task.progress}%</b></button>)}</div><form className="quick-add" onSubmit={e => { e.preventDefault(); const input=e.currentTarget.elements.title; if(input.value.trim()){onAddNote(input.value.trim()); input.value=''} }}><Plus/><input name="title" placeholder="오늘 할 일을 빠르게 추가하세요"/><button>추가</button></form></section><aside className="today-side"><section className="side-panel"><div className="section-title"><div><h2>오늘 일정</h2><p>예정된 일정</p></div><CalendarClock size={20}/></div>{events.length ? events.slice(0,3).map(e => <div className="event-row" key={e.id}><time>{new Date(e.start).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</time><i className={e.color}></i><div><strong>{e.title}</strong><small>{new Date(e.end).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}까지</small></div></div>) : <p className="empty">오늘 일정이 없습니다.</p>}</section><button className="ai-card" onClick={goAI}><span><Sparkles/></span><div><strong>AI에게 오늘 할 일 추천받기</strong><p>업무 진행 상황을 분석해 우선순위를 정리해 드려요.</p></div><ChevronRight/></button></aside><section className="log-panel"><div className="section-title"><div><h2>오늘 한 일</h2><p>짧게 기록해도 충분해요</p></div><Clock3/></div>{notes.length ? <div className="done-notes">{notes.map((n,i)=><div key={i}><Check/><span>{n}</span><time>오늘</time></div>)}</div> : <p className="empty">아직 기록이 없어요. 위 입력창에서 오늘 한 일을 남겨보세요.</p>}</section></div></>
}
