import { useState } from 'react'
import { CalendarClock, Check, ChevronRight, Circle, Clock3, Pencil, Plus, Sparkles, Trash2, X } from 'lucide-react'
import Header from '../components/Header'

const dateText = new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'long'}).format(new Date())

export default function Today({tasks,events,todos,logs,onAddTodo,onToggleTodo,onDeleteTodo,onAddLog,onUpdateLog,onDeleteLog,onToggleTask,goAI}) {
  const [editing,setEditing]=useState(null), [draft,setDraft]=useState('')
  const active=tasks.filter(t=>t.status!=='done').slice(0,5)
  const submitTodo=e=>{e.preventDefault();const value=e.currentTarget.elements.title.value.trim();if(value){onAddTodo(value);e.currentTarget.reset()}}
  const submitLog=e=>{e.preventDefault();const value=e.currentTarget.elements.content.value.trim();if(value){onAddLog(value);e.currentTarget.reset()}}
  return <><Header title="오늘" subtitle={`${dateText} · 중요한 일에 집중해 보세요.`}/><div className="content today-grid">
    <section className="focus-panel"><div className="section-title"><div><h2>오늘 할 일</h2><p>빠른 Todo와 진행 중인 업무를 함께 확인합니다.</p></div></div>
      <form className="quick-add" onSubmit={submitTodo}><Plus/><input name="title" aria-label="오늘 Todo" placeholder="오늘 꼭 할 일을 추가하세요"/><button>추가</button></form>
      {todos.length?<div className="todo-list">{todos.map(todo=><div className={`todo-row ${todo.completed?'completed':''}`} key={todo.id}><button className="todo-check" aria-label={`${todo.title} ${todo.completed?'미완료':'완료'} 처리`} onClick={()=>onToggleTodo(todo)}>{todo.completed?<Check/>:<Circle/>}</button><span>{todo.title}</span><button className="danger-icon" title="삭제" onClick={()=>onDeleteTodo(todo)}><Trash2/></button></div>)}</div>:null}
      <div className="section-divider"><span>등록된 업무</span><b>{active.length}</b></div><div className="task-list">{active.length?active.map(task=><button className="task-row" key={task.id} onClick={()=>onToggleTask(task)}><span className="check-circle"><Circle/><Check/></span><span className="task-main"><strong>{task.title}</strong><small>{task.priority==='high'?'높은 우선순위':'업무'} · {task.due_date||'기한 없음'}</small></span><span className="mini-progress"><i style={{width:`${task.progress}%`}}/></span><b>{task.progress}%</b></button>):<p className="empty-state">오늘 진행할 업무가 없습니다.</p>}</div></section>
    <aside className="today-side"><section className="side-panel"><div className="section-title"><div><h2>오늘 일정</h2><p>{events.length}개의 일정</p></div><CalendarClock/></div>{events.length?events.slice(0,4).map(e=><div className="event-row" key={e.id}><time>{new Date(e.start).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</time><i/><div><strong>{e.title}</strong><small>{e.location||'일정'}</small></div></div>):<p className="empty-state">오늘은 등록된 일정이 없습니다.</p>}</section><button className="ai-card" onClick={goAI}><span><Sparkles/></span><div><strong>AI에게 오늘 할 일 추천받기</strong><p>진행 상황과 마감일을 분석해 우선순위를 정리합니다.</p></div><ChevronRight/></button></aside>
    <section className="log-panel"><div className="section-title"><div><h2>오늘 한 일</h2><p>작은 성과도 기록하면 내일의 계획이 선명해집니다.</p></div><Clock3/></div><form className="quick-add" onSubmit={submitLog}><Plus/><input name="content" aria-label="오늘 한 일" placeholder="오늘 완료한 일을 기록하세요"/><button>기록</button></form>{logs.length?<div className="done-notes">{logs.map(log=><div key={log.id}>{editing===log.id?<><Check/><input className="inline-edit" value={draft} autoFocus onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&draft.trim()){onUpdateLog(log.id,draft.trim());setEditing(null)}if(e.key==='Escape')setEditing(null)}}/><span className="row-actions"><button title="취소" onClick={()=>setEditing(null)}><X/></button><button title="저장" onClick={()=>{if(draft.trim()){onUpdateLog(log.id,draft.trim());setEditing(null)}}}><Check/></button></span></>:<><Check/><span>{log.content}</span><span className="row-actions"><button title="수정" onClick={()=>{setEditing(log.id);setDraft(log.content)}}><Pencil/></button><button className="danger-icon" title="삭제" onClick={()=>onDeleteLog(log)}><Trash2/></button></span></>}</div>)}</div>:<p className="empty-state">아직 기록이 없습니다. 방금 끝낸 일부터 적어보세요.</p>}</section>
  </div></>
}
