import { useCallback, useEffect, useRef, useState } from 'react'
import { api, AUTH_EXPIRED_EVENT } from './api'
import { useTheme } from './hooks/useTheme'
import AppShell from './components/AppShell'; import Login from './components/Login'; import Modal from './components/Modal'; import ConfirmDialog from './components/ConfirmDialog'; import TaskForm from './components/TaskForm'; import Toast from './components/Toast'
import Today from './screens/Today'; import Tasks from './screens/Tasks'; import Calendar from './screens/Calendar'; import AIAssistant from './screens/AIAssistant'; import Settings from './screens/Settings'
import Changelog from './screens/Changelog'
import Performance from './screens/Performance'
import AuditLog from './screens/AuditLog'
import { loadTeamMembers, saveTeamMembers } from './teamMembers'
import { loadTeamMemberCapacities, saveTeamMemberCapacity } from './teamMemberCapacity'
import { upsertTask } from './taskState'

const eventColors=['blue','purple','orange']
const pages = ['today','tasks','calendar','performance','ai','audit','changelog','settings']
export default function App(){
 const {preference,setPreference}=useTheme(),[user,setUser]=useState(null),[boot,setBoot]=useState({loading:true,error:'',google:true}),[page,setPage]=useState(()=>{const p=new URLSearchParams(location.search).get('page');return pages.includes(p)?p:'today'})
 const [tasks,setTasks]=useState([]),[todayTasks,setTodayTasks]=useState([]),[events,setEvents]=useState([]),[todos,setTodos]=useState([]),[logs,setLogs]=useState([]),[dataLoading,setDataLoading]=useState(false),[dataError,setDataError]=useState('')
 const [modal,setModal]=useState(null),[confirm,setConfirm]=useState(null),[toast,setToast]=useState(null),[aiText,setAiText]=useState(''),[preview,setPreview]=useState(null),[recommendations,setRecommendations]=useState([]),[aiMode,setAiMode]=useState('parse'),[aiBusy,setAiBusy]=useState(false)
 const [installPrompt,setInstallPrompt]=useState(null),toastTimer=useRef(null)
 const [teamMembers,setTeamMembers]=useState(()=>loadTeamMembers(localStorage))
 const [teamMemberCapacities,setTeamMemberCapacities]=useState(()=>loadTeamMemberCapacities(localStorage))
 const [notificationPermission,setNotificationPermission]=useState(()=>('Notification' in window?Notification.permission:'unsupported'))
 const notify=useCallback((message,type='success')=>{setToast({message,type});clearTimeout(toastTimer.current);toastTimer.current=window.setTimeout(()=>setToast(null),4000)},[])
 const refresh=useCallback(async()=>{setDataLoading(true);setDataError('');try{const [allTasks,allEvents,today]=await Promise.all([api.tasks(),api.events(),api.today()]);setTasks(allTasks);setTodayTasks(today.tasks||[]);setEvents(allEvents.map((x,i)=>({...x,start:x.start_at,end:x.end_at,color:eventColors[i%eventColors.length]})));setTodos(today.todos||[]);setLogs(today.work_logs||[]);return true}catch(e){setDataError(e.message);notify(e.message,'error');return false}finally{setDataLoading(false)}},[notify])
 const refreshTasksOnly=useCallback(async()=>{const latestTasks=await api.tasks();setTasks(latestTasks)},[])
 const mergeSavedTask=useCallback(savedTask=>setTasks(current=>upsertTask(current,savedTask)),[])
 const bootstrap=useCallback(async()=>{setBoot(b=>({...b,loading:true,error:''}));const [configResult,userResult]=await Promise.allSettled([api.config(),api.me()]);const config=configResult.status==='fulfilled'?configResult.value:null,current=userResult.status==='fulfilled'?userResult.value:null,meUnavailable=userResult.status==='rejected'&&userResult.reason?.status!==401;setUser(current?.user||null);setBoot({loading:false,google:config?.google_enabled!==false,error:configResult.status==='rejected'||meUnavailable?'서비스에 연결할 수 없습니다. 잠시 후 다시 시도해 주세요.':''})},[])
 useEffect(()=>{bootstrap()},[bootstrap])
 useEffect(()=>{const install=e=>{e.preventDefault();setInstallPrompt(e)},updated=()=>notify('새 버전이 준비되었습니다. 앱을 다시 열면 자동으로 적용됩니다.');addEventListener('beforeinstallprompt',install);addEventListener('workmanager:update-ready',updated);return()=>{removeEventListener('beforeinstallprompt',install);removeEventListener('workmanager:update-ready',updated);clearTimeout(toastTimer.current)}},[notify])
 useEffect(()=>{if(location.pathname.replace(/\/+$/,'')==='/changelog')return;const url=new URL(location.href);url.searchParams.set('page',page);history.replaceState(null,'',url);const pop=()=>{const p=new URLSearchParams(location.search).get('page');if(pages.includes(p))setPage(p)};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[page])
 useEffect(()=>{const expired=()=>{setUser(null);setBoot(b=>({...b,error:'로그인 세션이 만료되었습니다. 다시 로그인해 주세요.'}))};window.addEventListener(AUTH_EXPIRED_EVENT,expired);return()=>window.removeEventListener(AUTH_EXPIRED_EVENT,expired)},[])
 useEffect(()=>{if(user)refresh()},[user,refresh])
 useEffect(()=>{const params=new URLSearchParams(location.search);if(user&&page==='tasks'&&params.get('action')==='new'){setModal({type:'task'});params.delete('action');history.replaceState(null,'',`${location.pathname}?${params}`)}},[user,page])
 useEffect(()=>{if(notificationPermission!=='granted'||!todayTasks.length)return;const day=new Date().toLocaleDateString('en-CA'),key=`wm-reminder-${day}`;if(localStorage.getItem(key))return;const due=todayTasks.filter(task=>task.status!=='done');if(due.length)navigator.serviceWorker?.ready.then(registration=>registration.showNotification('WorkManager 오늘의 업무',{body:due.length===1?due[0].title:`${due[0].title} 외 ${due.length-1}개 업무가 예정되어 있습니다.`,icon:'/icon.svg',tag:key}).then(()=>localStorage.setItem(key,'shown'))).catch(()=>{})},[notificationPermission,todayTasks])
 const mutate=useCallback(async(action,success,onError)=>{try{await action();const refreshed=await refresh();if(!refreshed)return false;if(success)notify(success);return true}catch(e){notify(e.message,'error');onError?.(e);return false}},[notify,refresh])
 const askDelete=useCallback((message,action,success)=>setConfirm({message,action,success,busy:false}),[])
 const runDelete=async()=>{setConfirm(c=>({...c,busy:true}));const ok=await mutate(confirm.action,confirm.success);if(ok)setConfirm(null);else setConfirm(c=>({...c,busy:false}))}
 const analyze=async()=>{setAiMode('parse');setAiBusy(true);try{setPreview(await api.aiPreview(aiText))}catch(e){notify(e.message,'error')}finally{setAiBusy(false)}}
 const recommend=async()=>{setAiMode('recommend');setPreview(null);setAiBusy(true);try{const result=await api.aiRecommendations(5);setRecommendations(result.items||[])}catch(e){notify(e.message,'error')}finally{setAiBusy(false)}}
 const apply=()=>mutate(async()=>{await api.aiApply({action:preview.action,entity:preview.entity,id:preview.id,data:preview.data});setPreview(null);setAiText('');setPage('today')},'AI 제안을 적용했습니다.')
 const updateTeamMembers=members=>setTeamMembers(saveTeamMembers(localStorage,members))
 const updateTeamMemberCapacity=(name,limit)=>setTeamMemberCapacities(current=>saveTeamMemberCapacity(localStorage,current,name,limit))
 if(location.pathname.replace(/\/+$/,'')==='/changelog')return <Changelog publicMode/>
 if(boot.loading)return <div className="app-loading" role="status"><span className="brand-mark">W</span><span>WorkManager를 준비하고 있습니다…</span></div>
 if(!user)return <Login error={boot.error} googleEnabled={boot.google} onRetry={bootstrap}/>
 const screens={
  today:<Today tasks={todayTasks} events={events} todos={todos} logs={logs} loading={dataLoading} onAddTodo={(title,tags)=>mutate(()=>api.createTodo({title,tags,todo_date:new Date().toLocaleDateString('en-CA'),completed:false}),'오늘 할 일을 추가했습니다.')} onUpdateTodo={(id,title,tags)=>mutate(()=>api.updateTodo(id,{title,tags}),'오늘 할 일을 수정했습니다.')} onToggleTodo={todo=>mutate(()=>api.updateTodo(todo.id,{completed:!todo.completed}))} onDeleteTodo={todo=>askDelete(`‘${todo.title}’ 할 일을 삭제합니다.`,()=>api.deleteTodo(todo.id),'오늘 할 일을 삭제했습니다.')} onAddLog={(content,tags)=>mutate(()=>api.createLog({content,tags,log_date:new Date().toLocaleDateString('en-CA')}),'오늘 한 일을 기록했습니다.')} onUpdateLog={(id,content,tags)=>mutate(()=>api.updateLog(id,{content,tags}),'기록을 수정했습니다.')} onDeleteLog={log=>askDelete(`‘${log.content}’ 기록을 삭제합니다.`,()=>api.deleteLog(log.id),'기록을 삭제했습니다.')} onToggleTask={t=>mutate(()=>api.updateTask(t.id,{progress:t.progress===100?0:100,status:t.progress===100?'todo':'done'}))} goAI={()=>setPage('ai')}/>,
  tasks:<Tasks tasks={tasks} teamMembers={teamMembers} onNew={()=>setModal({type:'task'})} onEdit={task=>setModal({type:'task',task})} onProgress={(t,value)=>mutate(()=>api.updateTask(t.id,{progress:value,status:value===100?'done':value>0?'doing':'todo'}),'진행률을 저장했습니다.')} onApprove={(t,data)=>mutate(()=>api.updateTask(t.id,data),data.approval_status==='approved'?'업무를 승인했습니다.':'업무를 재작업으로 돌렸습니다.')}/>,
  calendar:<Calendar events={events} notify={notify} onDataChanged={refresh} onCreate={data=>mutate(()=>api.createEvent(data),'일정을 등록했습니다.')} onUpdate={(event,data)=>mutate(()=>api.updateEvent(event.id,data),'일정을 수정했습니다.')} onDelete={event=>mutate(()=>api.deleteEvent(event.id),'일정을 삭제했습니다.')}/>,
  performance:<Performance notify={notify} onDataChanged={refresh}/>,
  ai:<AIAssistant text={aiText} setText={setAiText} preview={preview} recommendations={recommendations} mode={aiMode} loading={aiBusy} onPreview={analyze} onRecommend={recommend} onApply={apply}/>,
  audit:<AuditLog/>,
  changelog:<Changelog notify={notify}/>,
  settings:<Settings theme={preference} setTheme={setPreference} tasks={tasks} teamMembers={teamMembers} teamMemberCapacities={teamMemberCapacities} setTeamMemberCapacity={updateTeamMemberCapacity} setTeamMembers={updateTeamMembers} notify={notify} onDataChanged={refresh} canInstall={!!installPrompt} onInstall={async()=>{if(!installPrompt)return;await installPrompt.prompt();const result=await installPrompt.userChoice;if(result.outcome==='accepted')notify('WorkManager 앱을 설치했습니다.');setInstallPrompt(null)}} notificationPermission={notificationPermission} onEnableNotifications={async()=>{if(!('Notification' in window)){notify('이 브라우저는 알림을 지원하지 않습니다.','error');return}const result=await Notification.requestPermission();setNotificationPermission(result);notify(result==='granted'?'오늘 업무 알림을 켰습니다.':'브라우저 설정에서 알림 권한을 허용해 주세요.',result==='granted'?'success':'error')}}/>
 }
 return <AppShell page={page} setPage={setPage} onLogout={async()=>{try{await api.logout()}finally{setUser(null)}}} user={user}>{dataError?<div className="data-error" role="alert"><span>{dataError}</span><button onClick={refresh}>다시 시도</button></div>:null}{screens[page]}
  {modal?.type==='task'?<Modal title={modal.task?'업무 수정':'새 업무'} onClose={()=>setModal(null)}><TaskForm key={modal.task?.id ?? 'new-task'} task={modal.task} tasks={tasks} teamMembers={teamMembers} teamMemberCapacities={teamMemberCapacities} onSave={async data=>{try{const savedTask=await (modal.task?api.updateTask(modal.task.id,data):api.createTask(data));try{await refreshTasksOnly();notify(modal.task?'업무를 수정했습니다.':'업무를 추가했습니다.')}catch(e){mergeSavedTask(savedTask);notify('업무는 저장했지만 목록을 다시 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.','error')}setModal(null);return {ok:true,error:''}}catch(e){notify(e.message,'error');return {ok:false,error:e.message}}}} onDelete={modal.task?()=>askDelete(`‘${modal.task.title}’ 업무를 삭제합니다.`,async()=>{await api.deleteTask(modal.task.id);setModal(null)},'업무를 삭제했습니다.'):null} onCancel={()=>setModal(null)}/></Modal>:null}
  {confirm?<ConfirmDialog message={confirm.message} busy={confirm.busy} onClose={()=>setConfirm(null)} onConfirm={runDelete}/>:null}<Toast toast={toast} onClose={()=>setToast(null)}/></AppShell>
}
